USE Portafolio_BI;
GO

IF OBJECT_ID('stg.Trafico_Aereo', 'U') IS NOT NULL
    DROP TABLE stg.Trafico_Aereo;
GO

CREATE TABLE stg.Trafico_Aereo (
    [Año] INT NULL,
    [Mes] INT NULL,
    [Cod_Operador] NVARCHAR(255) NULL,
    [Operador] NVARCHAR(255) NULL,
    [Grupo] NVARCHAR(255) NULL,
    [ORIG_1] NVARCHAR(255) NULL,
    [DEST_1] NVARCHAR(255) NULL,
    [ORIG_1_N] NVARCHAR(255) NULL,
    [DEST_1_N] NVARCHAR(255) NULL,
    [ORIG_1_PAIS] NVARCHAR(255) NULL,
    [DEST_1_PAIS] NVARCHAR(255) NULL,
    [ORIG_2] NVARCHAR(255) NULL,
    [DEST_2] NVARCHAR(255) NULL,
    [ORIG_2_N] NVARCHAR(255) NULL,
    [DEST_2_N] NVARCHAR(255) NULL,
    [ORIG_2_PAIS] NVARCHAR(255) NULL,
    [DEST_2_PAIS] NVARCHAR(255) NULL,
    [OPER_2] NVARCHAR(255) NULL,
    [NAC] NVARCHAR(255) NULL,
    [PAX_LIB] FLOAT NULL,
    [PASAJEROS] FLOAT NULL,
    [CAR_LIB] FLOAT NULL,
    [CARGA_Ton] FLOAT NULL,
    [CORREO] FLOAT NULL,
    [Distancia] FLOAT NULL,
    [Fecha] DATE NULL
);
GO
